name: build packages

on:
  push:
    tags:
      - 'v*'
    branches:
      - 'master'
    pull_request:
      branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build packages
        run: ./build.sh
        env:
          ALPINEREPOKEY: ${{ secrets.ALPINEREPOKEY }}

      - name: Deploy repo
        uses: JamesIves/github-pages-deploy-action@3.7.1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ghpages
          FOLDER: repo
          CLEAN: true
          SINGLE_COMMIT: true
