name: build packages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build packages
        run: ./build.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: packages/src/x86_64/*
