name: build packages

on:
  push:
    tags:
      - 'v*'
    branches:
      - 'master'
    pull_request:
      branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build packages
        run: ./build.sh
        env:
          ALPINEREPOKEY: ${{ secrets.ALPINEREPOKEY }}

      - name: Deploy repo
        uses: JamesIves/github-pages-deploy-action@4.1.3
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          branch: ghpages
          folder: repo
          clean: true
          single-commit: true
